services:
  matchbox:
    build:
      context: ../matchbox/matchbox-server
      dockerfile: ../../matchbox_docker/Dockerfile.r4
      additional_contexts:
        ig_dir: ./igs
        certs_dir: ./certs
      platforms:
        - linux/amd64
        - linux/arm64
    image: croeder/matchbox:r4

  matchbox-r5:
    build:
      context: ../matchbox/matchbox-server
      dockerfile: ../../matchbox_docker/Dockerfile.r5
      additional_contexts:
        ig_dir: ./igs
        certs_dir: ./certs
      platforms:
        - linux/amd64
        - linux/arm64
    image: croeder/matchbox:r5

  matchbox-r5-1.0.0:
    build:
      context: ../matchbox/matchbox-server
      dockerfile: ../../matchbox_docker/Dockerfile.r5
      additional_contexts:
        ig_dir: ./igs
        certs_dir: ./certs
      args:
        IG_VERSION: "1.0.0"
      platforms:
        - linux/amd64
        - linux/arm64
    image: croeder/matchbox:r5-1.0.0

  matchbox-r5-1.0.1:
    build:
      context: ../matchbox/matchbox-server
      dockerfile: ../../matchbox_docker/Dockerfile.r5
      additional_contexts:
        ig_dir: ./igs
        certs_dir: ./certs
      args:
        IG_VERSION: "1.0.1"
      platforms:
        - linux/amd64
        - linux/arm64
    image: croeder/matchbox:r5-1.0.1
