services:
  matchbox:
    build:
      context: ../matchbox/matchbox-server
      dockerfile: ../../matchbox_docker/Dockerfile
      additional_contexts:
        ig_dir: ./igs
        certs_dir: ./certs
      platforms:
        - linux/amd64
        - linux/arm64
    image: croeder/matchbox:latest
