spring:
  datasource:
    url: "jdbc:h2:file:/database/h2"
    username: sa
    password: null
    driverClassName: org.h2.Driver
  jpa:
    properties:
      hibernate.dialect: ca.uhn.fhir.jpa.model.dialect.HapiFhirH2Dialect

hapi:
  fhir:
    fhir_version: R5
    implementationguides:
      fhiromop:
        name: hl7.fhir.uv.omop
        version: 1.0.1
        url: file:///igs/hl7.fhir.uv.omop-1.0.1.tgz

matchbox:
  fhir:
    context:
      txServer: https://enchilada:8081/r4
      translateMode: fallback
      omopIdSalt: ""
      onlyOneEngine: true
      igsPreloaded:
        - hl7.fhir.uv.omop#1.0.1
